---
title: "EmoSSR: demographics participants"
author: '[Antonio Schettino](https://osf.io/zbv65/ "Antonio Schettino")'
date: '`r Sys.Date()`'
output:
  html_document:
    theme: united
    highlight: tango
    code_folding: hide
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup_environment, echo = FALSE, warning = FALSE, message = FALSE}

### install packages
# install.packages(c("knitr", "tidyverse"),
#                  dependencies = TRUE)

### load packages
library(knitr)
library(tidyverse)

```

```{r summary_data, message = FALSE}

# setwd(paste0(getwd(), "/demographics")) # set working subdir

demogr.data <- read_csv("EmoSSR_demographics.csv") %>%
  mutate(
    exp = factor(exp,
                 levels = c("pilot1", "pilot2", "exp1", "exp2")), # sort pilots first
    participant = as.factor(participant),
    sex = as.factor(sex)
  )

summary.demograph.data <- demogr.data %>%
  group_by(exp) %>%
  summarize(
    N = n(),
    sex = paste0(
    length(which(sex == "F")), "F/",
    length(which(sex == "M")), "M"),
    age.median = median(age, na.rm = TRUE),
    age.median.abs.dev = mad(age, na.rm = TRUE),
    age.min = min(age, na.rm = TRUE),
    age.max = max(age, na.rm = TRUE)
  )

kable(summary.demograph.data, digits = 2)

```

***
***
